//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoProgramaciónAvanzada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DIRECCION__USUARIO
    {
        public int ID_DETALLE { get; set; }
        public string DETALLE_DIRECCION { get; set; }
        public Nullable<int> ID_DISTRITO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
