//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoProgramaciónAvanzada.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnseñanzaVoluntariaEntities : DbContext
    {
        public EnseñanzaVoluntariaEntities()
            : base("name=EnseñanzaVoluntariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALIFICACION_TUTORIA> CALIFICACION_TUTORIA { get; set; }
        public virtual DbSet<CANTON> CANTON { get; set; }
        public virtual DbSet<CURSOS> CURSOS { get; set; }
        public virtual DbSet<DETALLE_DIRECCION__INSTITUCION> DETALLE_DIRECCION__INSTITUCION { get; set; }
        public virtual DbSet<DETALLE_DIRECCION__USUARIO> DETALLE_DIRECCION__USUARIO { get; set; }
        public virtual DbSet<DISTRITO> DISTRITO { get; set; }
        public virtual DbSet<INSTITUCION> INSTITUCION { get; set; }
        public virtual DbSet<MATERIAL_TUTORIA> MATERIAL_TUTORIA { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<TUTORIA_CURSOS> TUTORIA_CURSOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
