//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoProgramaciónAvanzada.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TUTORIA_CURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUTORIA_CURSOS()
        {
            this.CALIFICACION_TUTORIA = new HashSet<CALIFICACION_TUTORIA>();
            this.MATERIAL_TUTORIA = new HashSet<MATERIAL_TUTORIA>();
        }

        [Display(Name = "Tutoría")]
        public int ID_TUTORIA_CURSOS { get; set; }
        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "{0} es requerido")]
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_INSTITUCION { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_CURSO { get; set; }
        [Display(Name = "Fecha y Hora")]
        [Required(ErrorMessage = "{0} es requerido")]
        public string FECHA_HORA { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALIFICACION_TUTORIA> CALIFICACION_TUTORIA { get; set; }
        public virtual CURSOS CURSOS { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_TUTORIA> MATERIAL_TUTORIA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
